# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.102.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    cocoapods

  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new beta build to TestFlight."
  desc "This will also make sure the profile is up to date."
  lane :beta_build do
    increment_build_number
    gym(scheme: "freesurf")
    pilot(skip_waiting_for_build_processing: true)
    commit_version_bump(message: '+version')
    notification(subtitle: "Completed build", message: "You will be emailed when the file has been processed!")
  end

  desc "This bumps the version one patch, sets the build number to 1, and submits a new beta build to TestFlight."
  desc "This will also make sure the profile is up to date."
  lane :beta_patch do
    increment_version_number(bump_type: "patch")
    increment_build_number(build_number: '1')
    gym(scheme: "freesurf")
    pilot(skip_waiting_for_build_processing: true)
    commit_version_bump(message: '+version')
    notification(subtitle: "Completed build", message: "You will be emailed when the file has been processed!")
  end

  desc "This bumps the version one patch, sets the build number to 1, and submits a new beta build to TestFlight."
  desc "This will also make sure the profile is up to date."
  lane :beta_minor do
    increment_version_number(bump_type: "minor")
    increment_build_number(build_number: '1')
    gym(scheme: "freesurf")
    pilot(skip_waiting_for_build_processing: true)
    commit_version_bump(message: '+version')
    notification(subtitle: "Completed build", message: "You will be emailed when the file has been processed!")
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
